### ISSUE TITLE
Crashes when breaking blocks anywhere

### ISSUE THREAD

**Issue by Mewtwoy** [SuperCoder7979/survivalisland#3]
Description: Exception ticking world

java.lang.NullPointerException
    at net.minecraft.world.World.isOutOfBuildLimitVertically(World:191)
    at net.minecraft.world.World.getBlockState(World:405)
    at net.minecraft.server.world.ServerWorld.handler$bjd000$tick(ServerWorld:5580)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at net.minecraft.server.MinecraftServer$$Lambda$7140/1572923663.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

**Comment by jaskarth** [comment]
I'll see what's up with this.

**Comment by Mewtwoy** [comment]
Second crash, same world, different result.

Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 2
    at java.util.ArrayList.add(ArrayList.java:459)
    at net.minecraft.block.LeavesBlock.handler$bja000$queue(LeavesBlock:1031)
    at net.minecraft.block.LeavesBlock.getStateForNeighborUpdate(LeavesBlock)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.getStateForNeighborUpdate(AbstractBlock:910)
    at net.minecraft.block.AbstractBlock$AbstractBlockState.updateNeighbors(AbstractBlock:852)
    at net.minecraft.world.World.setBlockState(World:265)
    at net.minecraft.world.World.setBlockState(World:217)
    at net.minecraft.client.network.ClientPlayerInteractionManager.breakBlock(ClientPlayerInteractionManager:117)
    at net.minecraft.client.network.ClientPlayerInteractionManager.updateBlockBreakingProgress(ClientPlayerInteractionManager:239)
    at net.minecraft.client.MinecraftClient.handleBlockBreaking(MinecraftClient:1359)
    at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1720)
    at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1534)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

**Comment by Mewtwoy** [comment]
Real crash reason found, closing.
